#ddev-generated
version: '3.7'

services:
  # This is the service name used when running ddev commands accepting the
  # --service flag.
  backstop:
    # This is the name of the container. It is recommended to follow the same
    # name convention used in the main docker-compose.yml file.
    container_name: ddev-${DDEV_SITENAME}-backstop
    build:
      context: './backstopBuild'
      args:
        BASE_IMAGE: backstopjs/backstopjs:6.1.3
        username: $USER
        uid: $DDEV_GID
        gid: $DDEV_UID
    user:  '$DDEV_UID:$DDEV_GID'
    # Add init to reap Chrome processes, as noted at
    # https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#running-puppeteer-in-docker
    init: true
    entrypoint: [ /entrypoint.sh ]
    volumes:
      - ../tests/backstop:/src
      - .:/mnt/ddev_config:ro
    shm_size: 1gb
    environment:
      DDEV_HOSTNAME: $DDEV_HOSTNAME
    # These labels ensure this service is discoverable by ddev.
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: ${DDEV_APPROOT}
    networks:
      ddev_default: null
      default: null
    # external_links:
    #   - ddev-router:anotherhost.ddev.site
